name: pytest

on: [push, pull_request]

jobs:
  test:
    strategy:
      matrix:
        python-version:
          - '3.7'
          - '3.8'
          - '3.9'
          - '3.10'
          - '3.11'
    runs-on: ubuntu-latest
    steps:
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip setuptools
          ls
          pip install -r requirements.txt
      - name: Run pytest
        run: |
          pytest tests/
